### ISSUE TITLE
http://jxcore.com/xil.sh doesn't seem to exist anymore

### ISSUE THREAD

**Issue by pirog** [jxcore/jxcore-release#1]
Likely related to the website down issue. 

Is there an alternate location for the install script?

**Comment by ktrzeciaknubisa** [comment]
Yeap, please take a look here [master/doc/INSTALLATION.md](https://github.com/jxcore/jxcore/blob/master/doc/INSTALLATION.md)

``` bash
$ curl https://raw.githubusercontent.com/jxcore/jxcore/master/tools/jx_install.sh | bash
```
